---
- name: Загрузка WordPress
  become: yes
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Извлечение WordPress
  become: yes
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Установка владельца
  become: yes
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    state: directory
    recurse: yes

- name: Создание базы WordPress
  become: yes
  shell: >
    mysql -uroot -p{{ mysql_root_password }} -e "CREATE DATABASE wordpress;"

- name: Создание юзера базы WordPress
  become: yes
  shell: >
    mysql -uroot -p{{ mysql_root_password }} -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'wp_password'; GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost'; FLUSH PRIVILEGES;"
