---
- name: Установка Docker и Docker Compose
  hosts: all
  become: yes
  vars_files: 
    - vault.yml

  vars:
    docker_compose_version: "1.29.2"
    docker_compose_dest: "/usr/local/bin/docker-compose"

  tasks:
    - name: Обновление индекса пакетов apt
      apt:
        update_cache: yes

    - name: Установка необходимых пакетов
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Добавление GPG-ключа Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Настройка стабильного репозитория
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
        filename: docker

    - name: Установка Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Определение переменной uname_s
      command: uname -s
      register: uname_s_result

    - name: Определение переменной uname_m
      command: uname -m
      register: uname_m_result

    - name: Установка Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ uname_s_result.stdout }}-{{ uname_m_result.stdout }}"
        dest: "{{ docker_compose_dest }}"
        mode: '0755'

    - name: Создание символической ссылки для docker-compose
      command: ln -s "{{ docker_compose_dest }}" /usr/bin/docker-compose
      args:
        creates: /usr/bin/docker-compose

    - name: Убедиться, что Docker запущен
      service:
        name: docker
        state: started
        enabled: yes
