---
- name: Пример парсинга строки с помощью регулярных выражений
  hosts: localhost
  gather_facts: no

  # Объявление переменной, содержащей строку для анализа
  vars:
    string: 'Hi test 12 edit slack TST2000 kljl TsT1230'

  tasks:
    # Таска 1: Запись строки в файл
    - name: Ищем и записываем строки
      lineinfile:
        # Путь к файлу, в который будет записана строка
        path: /tmp/test.txt
        # Создание файла, если он не существует
        create: yes
        # Строка, которая будет добавлена в файл
        line: "{{ string }}"
        # Указание, что строка должна присутствовать в файле
        state: present

    # Задача 2: Проверка строки с помощью регулярного выражения и вывод результата
    - name: Парсинг
      debug:
        msg: >
          {% if string is match('^(Hi.*|.*[A-Z0-9]{3,}|.*TsT1230$)') %}
          {{ string }}
          {% else %}
          No match
          {% endif %}
